# Лабораторная работа 2
Выполнили: Елизарова Юлия, Игошин Андрей, Кипаренко Илья, Кириленко Юлия, Клыков Вячеслав, Лепигина Анастасия

In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.max_columns', 50)
%matplotlib inline

In [12]:
info = pd.read_csv('ml-100k/u.info', sep = '\t', engine = 'python', names = ['info'])
info

             info
0       943 users
1      1682 items
2  100000 ratings

Датасет содержит 100 000 оценок 934 пользователями 1682 фильмов. Каждый пользователь оценил не менее 20 фильмов.

In [5]:
data = pd.read_csv('ml-100k/u.data', sep = '\t', engine = 'python', names = ['user_id', 'movie_id', 'rating', 'timestamp'])
data

       user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
5          298       474       4  884182806
6          115       265       2  881171488
7          253       465       5  891628467
8          305       451       3  886324817
9            6        86       3  883603013
10          62       257       2  879372434
11         286      1014       5  879781125
12         200       222       5  876042340
13         210        40       3  891035994
14         224        29       3  888104457
15         303       785       3  879485318
16         122       387       5  879270459
17         194       274       2  879539794
18         291      1042       4  874834944
19         234      1184       2  892079237
20         119       392       4  886176814
21         167       486       4  892738452
22         299       144       4  877881320
23         291       118       2  874833878
24         308         1       4  887736532
25          95       546       2  879196566
26          38        95       5  892430094
27         102       768       2  883748450
28          63       277       4  875747401
29         160       234       5  876861185
...        ...       ...     ...        ...
99970      449       120       1  879959573
99971      661       762       2  876037121
99972      721       874       3  877137447
99973      821       151       4  874792889
99974      764       596       3  876243046
99975      537       443       3  886031752
99976      618       628       2  891308019
99977      487       291       3  883445079
99978      113       975       5  875936424
99979      943       391       2  888640291
99980      864       685       4  888891900
99981      750       323       3  879445877
99982      279        64       1  875308510
99983      646       750       3  888528902
99984      654       370       2  887863914
99985      617       582       4  883789294
99986      913       690       3  880824288
99987      660       229       2  891406212
99988      421       498       4  892241344
99989      495      1091       4  888637503
99990      806       421       4  882388897
99991      676       538       4  892685437
99992      721       262       3  877137285
99993      913       209       2  881367150
99994      378        78       3  880056976
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

В наборе присутствуют 5 пар тренировочных и тестовых выборок для кросс-валидации. По 80 000 и 20 000 оценок соответственно.

In [9]:
data_train_1 = pd.read_csv('ml-100k/u1.base', sep = '\t', engine = 'python', names = ['user_id', 'movie_id', 'rating', 'timestamp'])
data_train_1

       user_id  movie_id  rating  timestamp
0            1         1       5  874965758
1            1         2       3  876893171
2            1         3       4  878542960
3            1         4       3  876893119
4            1         5       3  889751712
5            1         7       4  875071561
6            1         8       1  875072484
7            1         9       5  878543541
8            1        11       2  875072262
9            1        13       5  875071805
10           1        15       5  875071608
11           1        16       5  878543541
12           1        18       4  887432020
13           1        19       5  875071515
14           1        21       1  878542772
15           1        22       4  875072404
16           1        25       4  875071805
17           1        26       3  875072442
18           1        28       4  875072173
19           1        29       1  878542869
20           1        30       3  878542515
21           1        32       5  888732909
22           1        34       2  878542869
23           1        35       1  878542420
24           1        37       2  878543030
25           1        38       3  878543075
26           1        40       3  876893230
27           1        41       2  876892818
28           1        42       5  876892425
29           1        43       4  878542869
...        ...       ...     ...        ...
79970      943       720       1  888640048
79971      943       721       5  888639660
79972      943       722       3  888640208
79973      943       724       1  888639478
79974      943       732       4  888639789
79975      943       739       4  888639929
79976      943       756       2  875502146
79977      943       763       4  875501813
79978      943       765       3  888640227
79979      943       785       2  888640088
79980      943       794       3  888640143
79981      943       796       3  888640311
79982      943       808       4  888639868
79983      943       816       4  888640186
79984      943       824       4  875502483
79985      943       825       3  875502283
79986      943       831       2  875502283
79987      943       840       4  888693104
79988      943       928       5  875502074
79989      943       941       1  888639725
79990      943       943       5  888639614
79991      943      1011       2  875502560
79992      943      1028       2  875502096
79993      943      1044       3  888639903
79994      943      1047       2  875502146
79995      943      1067       2  875501756
79996      943      1074       4  888640250
79997      943      1188       3  888640250
79998      943      1228       3  888640275
79999      943      1330       3  888692465

[80000 rows x 4 columns]

In [10]:
data_test_1 = pd.read_csv('ml-100k/u1.test', sep = '\t', engine = 'python', names = ['user_id', 'movie_id', 'rating', 'timestamp'])
data_test_1

       user_id  movie_id  rating  timestamp
0            1         6       5  887431973
1            1        10       3  875693118
2            1        12       5  878542960
3            1        14       5  874965706
4            1        17       3  875073198
5            1        20       4  887431883
6            1        23       4  875072895
7            1        24       3  875071713
8            1        27       2  876892946
9            1        31       3  875072144
10           1        33       4  878542699
11           1        36       2  875073180
12           1        39       4  875072173
13           1        44       5  878543541
14           1        47       4  875072125
15           1        49       3  878542478
16           1        51       4  878543275
17           1        53       3  876893206
18           1        54       3  878543308
19           1        56       4  875072716
20           1        60       5  875072370
21           1        61       4  878542420
22           1        62       3  878542282
23           1        64       5  875072404
24           1        65       4  875072125
25           1        67       3  876893054
26           1        69       3  875072262
27           1        70       3  875072895
28           1        72       4  878542678
29           1        73       3  876892774
...        ...       ...     ...        ...
19970      454       418       3  888267128
19971      454       484       3  881960445
19972      454       487       4  888266565
19973      454       493       2  888267617
19974      454       633       2  881959745
19975      454      1063       4  881960029
19976      454      1299       2  888266991
19977      455       135       5  879111248
19978      455       282       3  879109664
19979      455       293       4  879109110
19980      455       629       3  879111371
19981      455       755       3  879112189
19982      456       175       3  881372946
19983      456       294       1  881375667
19984      456       715       3  881373697
19985      456       943       4  881372946
19986      457       182       4  882396659
19987      457       192       5  882395018
19988      457       366       4  882549287
19989      457       443       4  882396989
19990      457       636       4  882548466
19991      457       704       4  882397240
19992      457       708       4  882398002
19993      457       775       3  882551021
19994      458       144       4  886396390
19995      458       648       4  886395899
19996      458      1101       4  886397931
19997      459       934       3  879563639
19998      460        10       3  882912371
19999      462       682       5  886365231

[20000 rows x 4 columns]

Информация о каждом фильме включает в себя название, даты выхода в прокат и появления в магазинах, ссылку на IMDB и жанр. Причем один фильм может быть отнесен к нескольким жанрам.

In [66]:
items = pd.read_csv('ml-100k/u.item', sep = '|', engine = 'python', names = ['movie_id', 'movie_title', 'release_date', 'video_release_date', 'IMDb_URL', 'unknown', 'Action', 'Adventure', 'Animation', "Children's", 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'])
items

,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
5,6,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,01-Jan-1995,NaN,http://us.imdb.com/Title?Yao+a+yao+yao+dao+wai...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
6,7,Twelve Monkeys (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Twelve%20Monk...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
7,8,Babe (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Babe%20(1995),0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0
8,9,Dead Man Walking (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Dead%20Man%20...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
9,10,Richard III (1995),22-Jan-1996,NaN,http://us.imdb.com/M/title-exact?Richard%20III...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
10,11,Seven (Se7en) (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Se7en%20(1995),0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
11,12,"Usual Suspects, The (1995)",14-Aug-1995,NaN,http://us.imdb.com/M/title-exact?Usual%20Suspe...,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
12,13,Mighty Aphrodite (1995),30-Oct-1995,NaN,http://us.imdb.com/M/title-exact?Mighty%20Aphr...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
13,14,"Postino, Il (1994)",01-Jan-1994,NaN,"http://us.imdb.com/M/title-exact?Postino,%20Il...",0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
14,15,Mr. Holland's Opus (1995),29-Jan-1996,NaN,http://us.imdb.com/M/title-exact?Mr.%20Holland...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
15,16,French Twist (Gazon maudit) (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Gazon%20maudi...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
16,17,From Dusk Till Dawn (1996),05-Feb-1996,NaN,http://us.imdb.com/M/title-exact?From%20Dusk%2...,0,1,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0
17,18,"White Balloon, The (1995)",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Badkonake%20S...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
18,19,Antonia's Line (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Antonia%20(1995),0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
19,20,Angels and Insects (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Angels%20and%...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
20,21,Muppet Treasure Island (1996),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Muppet%20Trea...,0,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0
21,22,Braveheart (1995),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Braveheart%20...,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
22,23,Taxi Driver (1976),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Taxi%20Driver...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
23,24,Rumble in the Bronx (1995),23-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Hong%20Faan%2...,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
24,25,"Birdcage, The (1996)",08-Mar-1996,NaN,"http://us.imdb.com/M/title-exact?Birdcage,%20T...",0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
25,26,"Brothers McMullen, The (1995)",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Brothers%20Mc...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
26,27,Bad Boys (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Bad%20Boys%20...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,28,Apollo 13 (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Apollo%2013%2...,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
28,29,Batman Forever (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Batman%20Fore...,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0
29,30,Belle de jour (1967),01-Jan-1967,NaN,http://us.imdb.com/M/title-exact?Belle%20de%20...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1652,1653,Entertaining Angels: The Dorothy Day Story (1996),27-Sep-1996,NaN,http://us.imdb.com/M/title-exact?Entertaining%...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1653,1654,Chairman of the Board (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Chairman+of+the+Board...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1654,1655,"Favor, The (1994)",01-Jan-1994,NaN,"http://us.imdb.com/M/title-exact?Favor,%20The%...",0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
1655,1656,Little City (1998),20-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Little+City+(...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
1656,1657,Target (1995),28-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Target%20(1995),0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1657,1658,"Substance of Fire, The (1996)",06-Dec-1996,NaN,http://us.imdb.com/M/title-exact?Substance%20o...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1658,1659,Getting Away With Murder (1996),12-Apr-1996,NaN,http://us.imdb.com/Title?Getting+Away+With+Mur...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1659,1660,Small Faces (1995),09-Aug-1996,NaN,http://us.imdb.com/M/title-exact?Small%20Faces...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1660,1661,"New Age, The (1994)",01-Jan-1994,NaN,"http://us.imdb.com/M/title-exact?New%20Age,%20...",0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1661,1662,Rough Magic (1995),30-May-1997,NaN,http://us.imdb.com/M/title-exact?Rough%20Magic...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1662,1663,Nothing Personal (1995),30-Apr-1997,NaN,http://us.imdb.com/M/title-exact?Nothing%20Per...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
1663,1664,8 Heads in a Duffel Bag (1997),18-Apr-1997,NaN,http://us.imdb.com/Title?8+Heads+in+a+Duffel+B...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1664,1665,"Brother's Kiss, A (1997)",25-Apr-1997,NaN,http://us.imdb.com/M/title-exact?Brother%27s%2...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1665,1666,Ripe (1996),02-May-1997,NaN,http://us.imdb.com/M/title-exact?Ripe%20%28199...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1666,1667,"Next Step, The (1995)",13-Jun-1997,NaN,http://us.imdb.com/M/title-exact?Next%20Step%2...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1667,1668,Wedding Bell Blues (1996),13-Jun-1997,NaN,http://us.imdb.com/M/title-exact?Wedding%20Bel...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1668,1669,MURDER and murder (1996),20-Jun-1997,NaN,http://us.imdb.com/M/title-exact?MURDER+and+mu...,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0
1669,1670,Tainted (1998),01-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Tainted+(1998),0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
1670,1671,"Further Gesture, A (1996)",20-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Further+Gestu...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1671,1672,Kika (1993),01-Jan-1993,NaN,http://us.imdb.com/M/title-exact?Kika%20(1993),0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1672,1673,Mirage (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Mirage%20(1995),0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1673,1674,Mamma Roma (1962),01-Jan-1962,NaN,http://us.imdb.com/M/title-exact?Mamma%20Roma%...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1674,1675,"Sunchaser, The (1996)",25-Oct-1996,NaN,"http://us.imdb.com/M/title-exact?Sunchaser,%20...",0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1675,1676,"War at Home, The (1996)",01-Jan-1996,NaN,http://us.imdb.com/M/title-exact?War%20at%20Ho...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1676,1677,Sweet Nothing (1995),20-Sep-1996,NaN,http://us.imdb.com/M/title-exact?Sweet%20Nothi...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1677,1678,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [67]:
items.describe()

,movie_id,video_release_date,unknown,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
count,1682.000000,0.0,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.00000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000
mean,841.500000,NaN,0.001189,0.149227,0.080262,0.024970,0.072533,0.300238,0.064804,0.029727,0.431034,0.01308,0.014269,0.054697,0.033294,0.036266,0.146849,0.060048,0.149227,0.042212,0.016052
std,485.695893,NaN,0.034473,0.356418,0.271779,0.156081,0.259445,0.458498,0.246253,0.169882,0.495368,0.11365,0.118632,0.227455,0.179456,0.187008,0.354061,0.237646,0.356418,0.201131,0.125714
min,1.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,421.250000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,841.500000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1261.750000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1682.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

По представленной таблице можно сделать вывод, что столбец с датой выхода фильма в видеоформате не содержит ни одного значения и может быть удален. Остальные столбцы не содержат пустых значений и не нуждаются в обработке.

In [68]:
items = items.drop('video_release_date', axis=1)
items

,movie_id,movie_title,release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
5,6,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,01-Jan-1995,http://us.imdb.com/Title?Yao+a+yao+yao+dao+wai...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
6,7,Twelve Monkeys (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Twelve%20Monk...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
7,8,Babe (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Babe%20(1995),0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0
8,9,Dead Man Walking (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Dead%20Man%20...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
9,10,Richard III (1995),22-Jan-1996,http://us.imdb.com/M/title-exact?Richard%20III...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
10,11,Seven (Se7en) (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Se7en%20(1995),0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
11,12,"Usual Suspects, The (1995)",14-Aug-1995,http://us.imdb.com/M/title-exact?Usual%20Suspe...,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
12,13,Mighty Aphrodite (1995),30-Oct-1995,http://us.imdb.com/M/title-exact?Mighty%20Aphr...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
13,14,"Postino, Il (1994)",01-Jan-1994,"http://us.imdb.com/M/title-exact?Postino,%20Il...",0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
14,15,Mr. Holland's Opus (1995),29-Jan-1996,http://us.imdb.com/M/title-exact?Mr.%20Holland...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
15,16,French Twist (Gazon maudit) (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Gazon%20maudi...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
16,17,From Dusk Till Dawn (1996),05-Feb-1996,http://us.imdb.com/M/title-exact?From%20Dusk%2...,0,1,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0
17,18,"White Balloon, The (1995)",01-Jan-1995,http://us.imdb.com/M/title-exact?Badkonake%20S...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
18,19,Antonia's Line (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Antonia%20(1995),0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
19,20,Angels and Insects (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Angels%20and%...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
20,21,Muppet Treasure Island (1996),16-Feb-1996,http://us.imdb.com/M/title-exact?Muppet%20Trea...,0,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0
21,22,Braveheart (1995),16-Feb-1996,http://us.imdb.com/M/title-exact?Braveheart%20...,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
22,23,Taxi Driver (1976),16-Feb-1996,http://us.imdb.com/M/title-exact?Taxi%20Driver...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
23,24,Rumble in the Bronx (1995),23-Feb-1996,http://us.imdb.com/M/title-exact?Hong%20Faan%2...,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
24,25,"Birdcage, The (1996)",08-Mar-1996,"http://us.imdb.com/M/title-exact?Birdcage,%20T...",0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
25,26,"Brothers McMullen, The (1995)",01-Jan-1995,http://us.imdb.com/M/title-exact?Brothers%20Mc...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
26,27,Bad Boys (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Bad%20Boys%20...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,28,Apollo 13 (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Apollo%2013%2...,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
28,29,Batman Forever (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Batman%20Fore...,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0
29,30,Belle de jour (1967),01-Jan-1967,http://us.imdb.com/M/title-exact?Belle%20de%20...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1652,1653,Entertaining Angels: The Dorothy Day Story (1996),27-Sep-1996,http://us.imdb.com/M/title-exact?Entertaining%...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1653,1654,Chairman of the Board (1998),01-Jan-1998,http://us.imdb.com/Title?Chairman+of+the+Board...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1654,1655,"Favor, The (1994)",01-Jan-1994,"http://us.imdb.com/M/title-exact?Favor,%20The%...",0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
1655,1656,Little City (1998),20-Feb-1998,http://us.imdb.com/M/title-exact?Little+City+(...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
1656,1657,Target (1995),28-Feb-1996,http://us.imdb.com/M/title-exact?Target%20(1995),0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1657,1658,"Substance of Fire, The (1996)",06-Dec-1996,http://us.imdb.com/M/title-exact?Substance%20o...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1658,1659,Getting Away With Murder (1996),12-Apr-1996,http://us.imdb.com/Title?Getting+Away+With+Mur...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1659,1660,Small Faces (1995),09-Aug-1996,http://us.imdb.com/M/title-exact?Small%20Faces...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1660,1661,"New Age, The (1994)",01-Jan-1994,"http://us.imdb.com/M/title-exact?New%20Age,%20...",0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1661,1662,Rough Magic (1995),30-May-1997,http://us.imdb.com/M/title-exact?Rough%20Magic...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1662,1663,Nothing Personal (1995),30-Apr-1997,http://us.imdb.com/M/title-exact?Nothing%20Per...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
1663,1664,8 Heads in a Duffel Bag (1997),18-Apr-1997,http://us.imdb.com/Title?8+Heads+in+a+Duffel+B...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1664,1665,"Brother's Kiss, A (1997)",25-Apr-1997,http://us.imdb.com/M/title-exact?Brother%27s%2...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1665,1666,Ripe (1996),02-May-1997,http://us.imdb.com/M/title-exact?Ripe%20%28199...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1666,1667,"Next Step, The (1995)",13-Jun-1997,http://us.imdb.com/M/title-exact?Next%20Step%2...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1667,1668,Wedding Bell Blues (1996),13-Jun-1997,http://us.imdb.com/M/title-exact?Wedding%20Bel...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1668,1669,MURDER and murder (1996),20-Jun-1997,http://us.imdb.com/M/title-exact?MURDER+and+mu...,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0
1669,1670,Tainted (1998),01-Feb-1998,http://us.imdb.com/M/title-exact?Tainted+(1998),0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
1670,1671,"Further Gesture, A (1996)",20-Feb-1998,http://us.imdb.com/M/title-exact?Further+Gestu...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1671,1672,Kika (1993),01-Jan-1993,http://us.imdb.com/M/title-exact?Kika%20(1993),0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1672,1673,Mirage (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Mirage%20(1995),0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1673,1674,Mamma Roma (1962),01-Jan-1962,http://us.imdb.com/M/title-exact?Mamma%20Roma%...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1674,1675,"Sunchaser, The (1996)",25-Oct-1996,"http://us.imdb.com/M/title-exact?Sunchaser,%20...",0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1675,1676,"War at Home, The (1996)",01-Jan-1996,http://us.imdb.com/M/title-exact?War%20at%20Ho...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1676,1677,Sweet Nothing (1995),20-Sep-1996,http://us.imdb.com/M/title-exact?Sweet%20Nothi...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1677,1678,Mat' i syn (1997),06-Feb-1998,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

Столбцы с названием фильма и ссылкой не могут быть преобразованы в значимые для компьютера признаки, поэтому могут быть удалены. Даты выхода целесообразно заменить на года выхода и нормализовать столбец таким образом, чтобы все значения были в диапазоне 0-1.

In [69]:
items = items.drop(['movie_id', 'movie_title', 'IMDb_URL'], axis=1)
release_years = [int(item[-4:]) if type(item) == str else item for item in items['release_date']]
min(release_years) + max(release_years)
only_integers = [item for item in release_years if type(item)==int]
mean_year = sum(only_integers) / len(only_integers)
release_years = [(item-min(only_integers))/(max(only_integers)-min(only_integers)) if type(item) == int else (mean_year-min(only_integers))/(max(only_integers)-min(only_integers)) for item in release_years]
items['release_date'] = release_years
items

,movie_id,release_date,unknown,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,0.960526,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,0.960526,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,3,0.960526,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,4,0.960526,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,0.960526,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
5,6,0.960526,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
6,7,0.960526,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
7,8,0.960526,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0
8,9,0.960526,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
9,10,0.973684,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
10,11,0.960526,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
11,12,0.960526,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
12,13,0.960526,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
13,14,0.947368,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
14,15,0.973684,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
15,16,0.960526,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
16,17,0.973684,0,1,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0
17,18,0.960526,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
18,19,0.960526,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
19,20,0.960526,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
20,21,0.973684,0,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0
21,22,0.973684,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
22,23,0.973684,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
23,24,0.973684,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
24,25,0.973684,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
25,26,0.960526,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
26,27,0.960526,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,28,0.960526,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
28,29,0.960526,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0
29,30,0.592105,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1652,1653,0.973684,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1653,1654,1.000000,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1654,1655,0.947368,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
1655,1656,1.000000,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
1656,1657,0.973684,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1657,1658,0.973684,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1658,1659,0.973684,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1659,1660,0.973684,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1660,1661,0.947368,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1661,1662,0.986842,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1662,1663,0.986842,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
1663,1664,0.986842,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1664,1665,0.986842,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1665,1666,0.986842,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1666,1667,0.986842,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1667,1668,0.986842,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1668,1669,0.986842,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0
1669,1670,1.000000,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
1670,1671,1.000000,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1671,1672,0.934211,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1672,1673,0.960526,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1673,1674,0.526316,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1674,1675,0.973684,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1675,1676,0.973684,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1676,1677,0.973684,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1677,1678,1.000000,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1678,1679,1.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1679,1680,1.000000,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1680,1681,0.947368,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1681,1682,0.973684,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [70]:
users = pd.read_csv('ml-100k/u.user', sep = '|')
users

       1  24  M     technician  85711
0      2  53  F          other  94043
1      3  23  M         writer  32067
2      4  24  M     technician  43537
3      5  33  F          other  15213
4      6  42  M      executive  98101
5      7  57  M  administrator  91344
6      8  36  M  administrator  05201
7      9  29  M        student  01002
8     10  53  M         lawyer  90703
9     11  39  F          other  30329
10    12  28  F          other  06405
11    13  47  M       educator  29206
12    14  45  M      scientist  55106
13    15  49  F       educator  97301
14    16  21  M  entertainment  10309
15    17  30  M     programmer  06355
16    18  35  F          other  37212
17    19  40  M      librarian  02138
18    20  42  F      homemaker  95660
19    21  26  M         writer  30068
20    22  25  M         writer  40206
21    23  30  F         artist  48197
22    24  21  F         artist  94533
23    25  39  M       engineer  55107
24    26  49  M       engineer  21044
25    27  40  F      librarian  30030
26    28  32  M         writer  55369
27    29  41  M     programmer  94043
28    30   7  M        student  55436
29    31  24  M         artist  10003
..   ...  .. ..            ...    ...
912  914  44  F          other  08105
913  915  50  M  entertainment  60614
914  916  27  M       engineer  N2L5N
915  917  22  F        student  20006
916  918  40  M      scientist  70116
917  919  25  M          other  14216
918  920  30  F         artist  90008
919  921  20  F        student  98801
920  922  29  F  administrator  21114
921  923  21  M        student  E2E3R
922  924  29  M          other  11753
923  925  18  F       salesman  49036
924  926  49  M  entertainment  01701
925  927  23  M     programmer  55428
926  928  21  M        student  55408
927  929  44  M      scientist  53711
928  930  28  F      scientist  07310
929  931  60  M       educator  33556
930  932  58  M       educator  06437
931  933  28  M        student  48105
932  934  61  M       engineer  22902
933  935  42  M         doctor  66221
934  936  24  M          other  32789
935  937  48  M       educator  98072
936  938  38  F     technician  55038
937  939  26  F        student  33319
938  940  32  M  administrator  02215
939  941  20  M        student  97229
940  942  48  F      librarian  78209
941  943  22  M        student  77841

[942 rows x 5 columns]